# server/docker-compose.yml
services:
  api:
    build: .
    container_name: skilldrill-api
    env_file:
      - .env
    ports:
      - "8080:8080"     # host:container
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: skilldrill-mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped

volumes:
  mongo_data:
