name: CI (smoke)

on:
  pull_request:
    branches: [ main ]
    paths:
      - "client/**"
      - "server/**"
      - ".github/workflows/**"
      - "eslint.config.js"
  push:
    branches: [ main ]
    paths:
      - "client/**"
      - "server/**"

permissions:
  contents: read

jobs:
  client:
    name: Client build (smoke)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: client/package-lock.json

      - name: Install
        run: npm ci

      - name: Build (non-blocking)
        run: npm run build --if-present
        continue-on-error: true

  server:
    name: Server install (smoke)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: server/package-lock.json

      - name: Install
        run: npm ci

      - name: Build (non-blocking)
        run: npm run build --if-present
        continue-on-error: true
