name: CI

on:
  pull_request:
    branches: [main]
    paths:
      - "client/**"
      - "server/**"
      - ".github/workflows/**"
      - "eslint.config.js"
  push:
    branches: [main]
    paths:
      - "client/**"
      - "server/**"
      - ".github/workflows/**"
      - "eslint.config.js"

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  client:
    name: Client build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: client/package-lock.json
      - run: npm ci
      - run: npm run build --if-present
        # на PR не валим билдом, на push в main — валим
        continue-on-error: ${{ github.event_name == 'pull_request' }}

  server:
    name: Server build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: server/package-lock.json
      - run: npm ci
      - run: npm run build --if-present
        continue-on-error: ${{ github.event_name == 'pull_request' }}

  lint:
    name: ESLint & Prettier
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pkg: [client, server]
    defaults:
      run:
        working-directory: ${{ matrix.pkg }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ./${{ matrix.pkg }}/package-lock.json
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Prettier check
        run: npm run prettier:check
