name: Deploy Backend

on:
  push:
    branches: [main]
    paths:
      - "server/**"
      - "docker-compose.yml"
      - ".github/workflows/deploy-backend.yml"
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-backend
      cancel-in-progress: false
    env:
      DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
      DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_PORT: ${{ secrets.SSH_PORT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Load SSH key (ssh-agent)
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ env.SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p "${SSH_PORT:-22}" -H "${DEPLOY_HOST}" >> ~/.ssh/known_hosts

      - name: Ensure remote dirs
        run: |
          ssh -p "${SSH_PORT:-22}" "${DEPLOY_USER}@${DEPLOY_HOST}" 'mkdir -p "$HOME/skilldrill/server"'

      - name: Sync backend files
        run: |
          rsync -az --delete --exclude node_modules --exclude .git \
            -e "ssh -p ${SSH_PORT:-22}" \
            ./server/ "${DEPLOY_USER}@${DEPLOY_HOST}:~/skilldrill/server/"

      - name: Sync compose file
        run: |
          rsync -az -e "ssh -p ${SSH_PORT:-22}" \
            ./docker-compose.yml "${DEPLOY_USER}@${DEPLOY_HOST}:~/skilldrill/"

      - name: Compose up on server
        run: |
          ssh -p "${SSH_PORT:-22}" "${DEPLOY_USER}@${DEPLOY_HOST}" << 'EOF'
            set -euo pipefail
            cd "$HOME/skilldrill"
            docker compose pull || true
            docker compose up -d --build
            docker compose ps
          EOF
