name: Deploy Frontend

on:
  push:
    branches: [main]
    paths:
      - "client/**"
      - ".github/workflows/deploy-frontend.yml"
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-frontend
      cancel-in-progress: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: client/package-lock.json

      - name: Build (client)
        working-directory: client
        env:
          HUSKY: 0
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
          VITE_AUTH_STUB: ${{ secrets.VITE_AUTH_STUB }}
        run: |
          npm ci
          npm run build

      - name: Prep known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ secrets.DEPLOY_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy via rsync over SSH
        uses: Burnett01/rsync-deployments@7.0.2
        with:
          switches: -avz --delete
          path: ./client/dist/
          remote_path: /var/www/skilldrill/
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
