name: Deploy Backend

on:
  push:
    branches: [main]
    paths:
      - "server/**"
      - "docker-compose.yml"
      - ".github/workflows/deploy-backend.yml"
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-backend
      cancel-in-progress: false
    env:
      DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
      DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_PORT: ${{ secrets.DEPLOY_SSH_PORT }}

    steps:
      - name: Checkout (context only)
        uses: actions/checkout@v4

      - name: Load SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ env.SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p "${SSH_PORT:-22}" -H "${DEPLOY_HOST}" >> ~/.ssh/known_hosts

      - name: Deploy (git reset + docker compose up)
        run: |
          ssh -p "${SSH_PORT:-22}" "${DEPLOY_USER}@${DEPLOY_HOST}" << 'EOF'
            set -euo pipefail

            # Константы для удалённой машины (без внешних env — не будет "unbound variable")
            DEPLOY_DIR=/opt/skilldrill
            REPO_BRANCH=main

            mkdir -p "$DEPLOY_DIR"

            # Уберём "dubious ownership" для git
            git config --global --add safe.directory "$DEPLOY_DIR"
            git config --global --add safe.directory "$DEPLOY_DIR/.git"

            # Проверим, что там git-репозиторий (если нет — дадим понятную подсказку и выходим)
            if [ ! -d "$DEPLOY_DIR/.git" ]; then
              echo "::error::$DEPLOY_DIR не является git-репозиторием."
              echo "::error::Один раз на сервере выполните:"
              echo "  git clone <SSH-URL-ВАШЕГО-РЕПО> $DEPLOY_DIR"
              echo "  cd $DEPLOY_DIR && git checkout $REPO_BRANCH"
              exit 1
            fi

            cd "$DEPLOY_DIR"

            # Обновляем код
            git fetch --all --prune
            git reset --hard "origin/$REPO_BRANCH"

            # Пересобираем и поднимаем контейнеры
            docker compose pull || true
            docker compose up -d --build

            # Короткий статус
            docker compose ps

            # При желании можно включить healthcheck:
            # curl -fsS http://127.0.0.1:8080/health || (docker logs --tail=200 skilldrill-api && exit 1)
          EOF
