name: Lint and Prettier Check

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: client/package-lock.json

      - name: Install deps (client)
        run: npm ci

      # Добираем плоскую конфигурацию ESLint, которую импортирует корневой eslint.config.js
      - name: Ensure flat-config deps
        run: npm i -D @eslint/js

      - name: ESLint (client + server, root config)
        run: npx eslint --config ../eslint.config.js . ../server --ext js,ts,tsx

      - name: Prettier check (client + server)
        run: npx prettier --check . ../server
